### ISSUE TITLE
Vertex for Elementary

### ISSUE THREAD

**Issue by bil-elmoussaoui** [horst3180/Vertex-theme#82] opened 2015-04-07 19:50 UTC
Hello,
I would like to report that vertex for elementary looks a little bit ugly in slinghtshot especially when you mouse hover an icon. the applications gets a black border. You can try that with Numix circle so you can see what i mean..
And i have one more question : Why some Gtk2 (headbars? i'm not sure about this)apps dosen't use the same color as gtk3 apps?

Sorry i couldn't take a screenshot.
Thank you very much!!

**Comment by horst3180** [comment] 2015-04-07 21:07
Are you running a fully updated Freya installation? This is the only supported version of elementary OS.

**Comment by bil-elmoussaoui** [comment] 2015-04-07 21:10
Yes with GTK 3.14 and Ferya 0.3 beta 2 , i don't know if i should give you more informations?

**Comment by horst3180** [comment] 2015-04-07 21:27
Hmm, unless something has changed it should work fine, but Freya is a moving target right now and things can break during updates. Some screenshots would be very helpful, though. Is there a reason you couldn't take one?

**Comment by bil-elmoussaoui** [comment] 2015-04-07 21:46
Well for the gtk2 apps the headbars looks like that
![gtk2 apps](https://cloud.githubusercontent.com/assets/7660997/7034078/56ef2e02-dd7f-11e4-9557-c2ee7e8154bb.png)
And for the gtk3 apps (Pantheon-files) the headbars 
![capture du 2015-04-07 23 37 05](https://cloud.githubusercontent.com/assets/7660997/7034093/6a3c6650-dd7f-11e4-96db-91935591e472.png)
For the slingshot bug i don't know if you can see it very clearly as i couldn't take a "zoomed" screenshot and hovering an icon in the same time 
![capture du 2015-04-07 23 38 12](https://cloud.githubusercontent.com/assets/7660997/7034118/98b22592-dd7f-11e4-9574-c05a2b2c57bb.png)

i still have one more bug to report: 
the black themed notifications look really elegant and i do love the choice of color! but Ferya uses black for icons like wifi, sound and brightness indicator so i don't think it's the best idea to keep using the black notifications.. 
![capture du 2015-04-07 23 43 38](https://cloud.githubusercontent.com/assets/7660997/7034195/1878de6a-dd80-11e4-8225-f1e5a9cf17ad.png)

Hope this will help you improve this theme.
One last thing, is there any official ppa? or should i keep checking on the github repo for new updates? :+1:

**Comment by horst3180** [comment] 2015-04-07 22:11
The first problem should be fixed by restarting the window manager. Executing `gala --replace &` should do the trick, but I don't know if it messes up the rest of the session, so rebooting would be the safest option. Sometimes the window manager doesn't pick up the colors correctly when you switch themes.

Slingshot looks as intended. I know the elementary theme styles this differently, but I did it this way so it's consistent with the other buttons.

The notification style is a bit of a problem, I agree. I will make them light, so they work with the default icon theme.

**Comment by bil-elmoussaoui** [comment] 2015-04-07 22:19
For the Slingshot, i really didn't explain very well the "bug", well if you make a zoom on the screenshot that i shared the Blender icon will look like this with a black border around it ? You can see that in almost every icon even the smallest ones in settings (Elementary Tweaks for example)
![capture du 2015-04-08 00 14 36](https://cloud.githubusercontent.com/assets/7660997/7034931/62d01ede-dd84-11e4-8128-543e61906e45.png)

One last thing (i hope)
The restart/shutdown prompt message looks like that using elementary theme
![capture du 2015-04-08 00 13 31](https://cloud.githubusercontent.com/assets/7660997/7034971/a7345220-dd84-11e4-8ac7-c259d1f3eec1.png)
and like that using Vertex theme
![capture du 2015-04-08 00 06 20](https://cloud.githubusercontent.com/assets/7660997/7034985/cf438a92-dd84-11e4-8ab4-f4a6ae6fe7a0.png)
I don't know if the headerbar is useful in this case? if not it would be cool to remove it.
And again, Thank you!!

**Comment by horst3180** [comment] 2015-04-07 22:41
I think I see the icon issue now. It might be an icon-shadow that got inherited from somewhere, I'll see what I can do.

You are right about the headerbar, it's not really useful and looks a bit out of place there. I can't remove the headerbar, but certainly the border and the gradient, so it would look like it's a part of the background.

**Comment by bil-elmoussaoui** [comment] 2015-04-08 10:25
Thank you for the quick answer; 
I did found an other little issue; when i use Geary some buttons aren't readable. You can see that in this screenshot. The font color is wihte in a gray background.
![capture du 2015-04-08 12 19 37](https://cloud.githubusercontent.com/assets/7660997/7043486/2bba8c70-ddea-11e4-85bc-d571e95800df.png)
I don't know if i have to open a new issue for others issues in Elementary or just to comment here?

**Comment by horst3180** [comment] 2015-04-08 17:23
Unfortunately the button issue seems to be a bug in `webkitgtk`. For some reason the buttons use the text color of pressed buttons. I haven't found a workaround for this, yet.

**Comment by horst3180** [comment] 2015-04-21 20:44
I made the notifications light in the default and light variants.
I thought about the header-bar in the logout dialog and I think I will keep it. The reason for this is that other dialogs use this too and there it's useful to drag the window.

**Comment by bil-elmoussaoui** [comment] 2015-04-21 20:46
Well, there's maybe a way to theme only the shutdown dialog like in the default theme? And thanks for the update !

**Comment by horst3180** [comment] 2015-04-21 21:04
Maybe, I'll have a look. Btw. I just removed that image highlight effect from slingshot.

**Comment by horst3180** [comment] 2015-04-21 21:36
Ok, it doesn't seem that it's possible. Elementary has this style for all dialog windows, that's because it works there, but as I said I don't want that.
You asked earlier if there was a ppa. Maybe you have seen that there are packages available for a few distros from Open Build Service. There are Ubuntu 14.04 and 14.10 packages, but unfortunately they won't work with Freya, because Ubuntu uses an older version of Gtk.
When Ubuntu 15.04 gets released, I can build deb packages with Gtk 3.14 support which should work with Freya, too.

**Closed** 2015-04-23 11:24 UTC
