### ISSUE TITLE
Budgie's power menu strings invisible

### ISSUE THREAD

**Issue by bmeznarsic** [horst3180/Vertex-theme#47] opened 2015-01-20 06:06 UTC
The options for shutting down, restarting etc. in the power menu seem to be invisible until I hover over them with the mouse. Issue might be related with the recent version bump of the GNOME stack/GTK+ to 3.14.

![zaslonska slika 2015-01-20 06 56 28](https://cloud.githubusercontent.com/assets/6306479/5812848/daee15be-a072-11e4-8635-dcc3c454dc9e.png)
![zaslonska slika 2015-01-20 07 00 09](https://cloud.githubusercontent.com/assets/6306479/5812847/dae9516e-a072-11e4-8887-22e60e29a7ae.png)
.

**Comment by vantu5z** [comment] 2015-01-20 06:46
I can't reproduce the issue. What gnome shell theme do you use?
With Vertex theme i have dialog like this:
![2015-01-20 09 38 52](https://cloud.githubusercontent.com/assets/8698003/5813099/b1da8e30-a088-11e4-8307-8bcac06693ea.png)

**Comment by bmeznarsic** [comment] 2015-01-20 06:48
This is on Evolve OS. I'm using budgie-desktop.

**Comment by horst3180** [comment] 2015-01-20 11:40
Hi, it should be fixed now. See 8899557f5092f9ca6874fd17bf4636fcb7239dbc

**Comment by bmeznarsic** [comment] 2015-01-20 11:49
Fixed! \o/ Thanks, dude! :))
![zaslonska slika 2015-01-20 12 47 17](https://cloud.githubusercontent.com/assets/6306479/5816629/92659ec2-a0a2-11e4-9c92-81234c13f306.png)

**Closed** 2015-01-20 11:52 UTC
